# Generated by Django 6.0.1 on 2026-01-26 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTER', 'Register'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VEHICLE_ADD', 'Vehicle Added'), ('BOOKING_CREATE', 'Booking Created'), ('BOOKING_CANCEL', 'Booking Cancelled'), ('ROLE_CHANGE', 'Role Changed')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
