# Generated by Django 6.0.1 on 2026-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('COSTUMER', 'Costumer'), ('ADMIN', 'Admin')], default='COSTUMER', max_length=25),
        ),
    ]
