# Generated by Django 6.0.1 on 2026-01-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_owner_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
