# Generated by Django 6.0.1 on 2026-01-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('LUXURY', 'Luxury'), ('FAMILY', 'Family'), ('BUSINESS', 'Business')], default='ECONOMY', max_length=25),
        ),
    ]
