# Generated by Django 6.0.1 on 2026-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
