# Generated by Django 6.0.1 on 2026-01-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='passenger',
            new_name='passengers',
        ),
    ]
