# Generated by Django 6.0.1 on 2026-01-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_passenger_booking_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
    ]
