# Generated by Django 6.0.1 on 2026-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_options_booking_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
