# Generated by Django 6.0.1 on 2026-03-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_dropoff_location_booking_dropoff_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='costumer',
            new_name='customer',
        ),
    ]
